name: cca_mlflow
channels:
  - conda-forge
dependencies:
  - python=3.13
  - mlflow=3.8
  - pandas=2.3
  - numpy=2.4
  - scikit-learn=1.8
  - matplotlib-base=3.10
  - pyyaml=6.0
  - fastapi=0.128
  - uvicorn=0.40
  - pip
  - pip:
      - xgboost==3.1.2